# Generated by Django 6.0.2 on 2026-06-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_rub', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Использование',
                'verbose_name_plural': 'Использование',
                'ordering': ('-day',),
                'indexes': [models.Index(fields=['user', 'day'], name='usage_usage_user_id_28fe4e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='unique_usage_per_user_per_day')],
            },
        ),
    ]
