# Generated by Django 6.0.2 on 2026-07-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_conversation_options_conversation_pinned'),
        ('usage', '0001_initial'),
        ('users', '0005_alter_userprofile_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('chat', 'Общий'), ('code', 'Код'), ('research', 'Модели')], max_length=20)),
                ('scenario', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('cost_rub', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие расхода ИИ',
                'verbose_name_plural': 'События расхода ИИ',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='usage',
            name='unique_usage_per_user_per_day',
        ),
        migrations.AddField(
            model_name='usage',
            name='mode',
            field=models.CharField(choices=[('chat', 'Общий'), ('code', 'Код'), ('research', 'Модели')], default='chat', max_length=20),
        ),
        migrations.AddIndex(
            model_name='usage',
            index=models.Index(fields=['user', 'day', 'mode'], name='usage_usage_user_id_85cc29_idx'),
        ),
        migrations.AddConstraint(
            model_name='usage',
            constraint=models.UniqueConstraint(fields=('user', 'day', 'mode'), name='unique_usage_per_user_per_day_per_mode'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='conversations.conversation'),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'created_at'], name='usage_usage_user_id_e1172f_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'mode', 'created_at'], name='usage_usage_user_id_9bdab8_idx'),
        ),
    ]
