# Generated by Django 6.0.2 on 2026-09-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0006_usageevent_degraded'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='thinking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='thinking_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
