# Generated by Django 6.0.2 on 2026-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0007_usageevent_thinking_usageevent_thinking_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='effort',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
