# Generated by Django 6.0.2 on 2026-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0008_usageevent_effort_usageevent_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usageevent',
            name='cache_read_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='cache_write_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
