# Generated by Django 6.0.2 on 2026-06-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Бесплатный'), ('pro', 'Pro')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('active', 'Активна'), ('past_due', 'Просрочена'), ('canceled', 'Отменена')], default='pending', max_length=20)),
                ('provider', models.CharField(default='yookassa', max_length=30)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='billing_sub_user_id_fe5b98_idx')],
            },
        ),
    ]
