# Generated by Django 6.0.2 on 2026-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20),
        ),
    ]
