# Generated by Django 6.0.2 on 2026-08-22 04:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_manual_subscriptions'),
        ('users', '0011_emailtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consent_given', 'Согласие на автосписания'), ('autorenew_on', 'Автопродление включено'), ('autorenew_off', 'Автопродление отключено'), ('method_deleted', 'Платёжное средство удалено'), ('renewal_notified', 'Уведомление о списании'), ('charged', 'Списание проведено'), ('charge_failed', 'Списание не прошло'), ('refunded', 'Возврат')], max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие биллинга',
                'verbose_name_plural': 'События биллинга',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('plan', models.CharField(choices=[('free', 'Бесплатный'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20)),
                ('kind', models.CharField(choices=[('initial', 'Первый платёж'), ('renewal', 'Автопродление'), ('upgrade', 'Смена тарифа')], default='initial', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('waiting_for_capture', 'Ожидает подтверждения'), ('succeeded', 'Оплачен'), ('canceled', 'Отменён')], default='pending', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('provider', models.CharField(default='yookassa', max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('idempotence_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('confirmation_url', models.URLField(blank=True, max_length=1000)),
                ('description', models.CharField(max_length=128)),
                ('auto_renew_requested', models.BooleanField(default=False)),
                ('consent_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('payment_method_id', models.CharField(blank=True, max_length=255)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_type', models.CharField(blank=True, max_length=32)),
                ('cancellation_reason', models.CharField(blank=True, max_length=100)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('idempotence_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('succeeded', 'Проведён'), ('canceled', 'Отклонён')], default='pending', max_length=20)),
                ('reason', models.CharField(choices=[('withdrawal', 'Отказ от услуги (п. 11.1)'), ('no_notice', 'Списание без уведомления (п. 7.6)'), ('after_cancel', 'Списание после отказа (п. 7.6)'), ('service_fault', 'Вина Исполнителя (п. 11.4)'), ('other', 'Иное')], default='withdrawal', max_length=30)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_by', models.CharField(default='system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Возврат',
                'verbose_name_plural': 'Возвраты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew',
            field=models.BooleanField(default=False, verbose_name='Автопродление'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='auto_renew_consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='subscription',
            name='card_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='subscription',
            name='offer_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='renewal_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='users.userprofile'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['auto_renew', 'current_period_end'], name='billing_sub_auto_re_753dfe_idx'),
        ),
        migrations.AddField(
            model_name='billingevent',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='billingevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_events', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='billing.subscription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='users.userprofile'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.payment'),
        ),
        migrations.AddIndex(
            model_name='billingevent',
            index=models.Index(fields=['user', '-created_at'], name='billing_bil_user_id_c81c87_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user', '-created_at'], name='billing_pay_user_id_c9be81_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='billing_pay_status_f64990_idx'),
        ),
    ]
