# Generated by Django 6.0.2 on 2026-08-22 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='npd_receipt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='npd_receipt_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
