# Generated by Django 6.0.2 on 2026-09-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_auto_renew_binding'),
        ('users', '0012_alter_usersettings_custom_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('trial', 'Пробный Plus'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('trial', 'Пробный Plus'), ('plus', 'Plus'), ('pro', 'Pro')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('plan', 'trial')), fields=('user', 'plan'), name='one_trial_per_user'),
        ),
    ]
