# Generated by Django 6.0.2 on 2026-07-02 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0002_alter_conversation_options_conversation_pinned'),
        ('users', '0004_remove_usersettings_show_suggestions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('source_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_facts', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Факт памяти',
                'verbose_name_plural': 'Факты памяти',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='memory_user_user_id_252f4f_idx')],
            },
        ),
    ]
