# Generated by Django 6.0.2 on 2026-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('letter', models.CharField(db_index=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Ошибка')], max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отправленное письмо',
                'verbose_name_plural': 'Отправленные письма',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['to_email', '-created_at'], name='mailer_sent_to_emai_5fda74_idx'), models.Index(fields=['status', '-created_at'], name='mailer_sent_status_0899ab_idx')],
            },
        ),
    ]
