# Generated by Django 6.0.2 on 2026-06-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('plan', models.CharField(choices=[('free', 'Бесплатный'), ('pro', 'Pro')], default='free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'indexes': [models.Index(fields=['plan'], name='users_userp_plan_12e6de_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_model', models.CharField(blank=True, max_length=50)),
                ('temperature', models.FloatField(default=0.7)),
                ('interface_lang', models.CharField(default='ru', max_length=10)),
                ('theme', models.CharField(default='system', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
