# Generated by Django 6.0.2 on 2026-06-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='auto_memory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='auto_scroll',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='context_size',
            field=models.CharField(default='20', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='custom_about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='custom_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='font_size',
            field=models.CharField(choices=[('sm', 'Мелкий'), ('md', 'Средний'), ('lg', 'Крупный')], default='md', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='occupation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='response_length',
            field=models.CharField(choices=[('short', 'Короткие'), ('balanced', 'Средние'), ('detailed', 'Подробные')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='show_suggestions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='streaming',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='web_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='theme',
            field=models.CharField(choices=[('system', 'Системная'), ('light', 'Светлая'), ('dark', 'Тёмная')], default='system', max_length=20),
        ),
    ]
