# Generated by Django 6.0.2 on 2026-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings_auto_memory_usersettings_auto_scroll_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='context_size',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='default_model',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='response_length',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='streaming',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='web_search',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='chat_model',
            field=models.CharField(choices=[('default', 'Стандартная'), ('fast', 'Быстрая'), ('quality', 'Максимальная')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='code_model',
            field=models.CharField(choices=[('default', 'Стандартная'), ('fast', 'Быстрая'), ('quality', 'Максимальная')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='context_depth',
            field=models.CharField(choices=[('compact', 'Компактно'), ('normal', 'Обычно'), ('deep', 'Глубоко'), ('maximum', 'Максимум')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='creativity',
            field=models.CharField(choices=[('precise', 'Точный'), ('balanced', 'Сбалансированный'), ('creative', 'Творческий')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='education_level',
            field=models.CharField(blank=True, choices=[('', 'Не указано'), ('school', 'Школа'), ('college', 'Колледж / СПО'), ('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('postgraduate', 'Аспирантура'), ('other', 'Другое')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='learning_goals',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='memory_scope',
            field=models.CharField(choices=[('minimal', 'Минимальный'), ('balanced', 'Сбалансированный'), ('detailed', 'Подробный')], default='balanced', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='memory_use',
            field=models.CharField(choices=[('off', 'Не использовать'), ('auto', 'Автоматически'), ('always', 'Всегда')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='reasoning_depth',
            field=models.CharField(choices=[('fast', 'Быстро'), ('auto', 'Авто'), ('deep', 'Тщательно')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='research_model',
            field=models.CharField(choices=[('default', 'Стандартная'), ('fast', 'Быстрая'), ('quality', 'Максимальная')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='response_length_preference',
            field=models.CharField(choices=[('shorter', 'Короче'), ('default', 'Как в сценарии'), ('longer', 'Подробнее')], default='default', max_length=20),
        ),
    ]
