# Generated by Django 6.0.2 on 2026-07-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usersettings_context_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='show_suggestions',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='chat_retention_days',
            field=models.PositiveIntegerField(choices=[(0, 'Не удалять'), (30, 'Старше 30 дней'), (90, 'Старше 90 дней'), (180, 'Старше 180 дней')], default=0),
        ),
    ]
