# Generated by Django 6.0.2 on 2026-07-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usersettings_show_suggestions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Бесплатный'), ('plus', 'Plus'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
