# Generated by Django 6.0.2 on 2026-07-13 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='auto_scroll',
        ),
    ]
