# Generated by Django 6.0.2 on 2026-07-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usersettings_auto_scroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='interface_lang',
        ),
    ]
