# Generated by Django 6.0.2 on 2026-08-15 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_local_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('verify_email', 'Подтверждение почты'), ('password_reset', 'Сброс пароля')], max_length=20)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_tokens', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Токен из письма',
                'verbose_name_plural': 'Токены из писем',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose'], name='users_email_user_id_91cb8a_idx')],
            },
        ),
    ]
