# Generated by Django 6.0.2 on 2026-07-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Ответ'), ('notice', 'Уведомление системы')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
