# Generated by Django 6.0.2 on 2026-07-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_message_kind_message_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='scenario_id',
            field=models.CharField(blank=True, default='', max_length=40),
            preserve_default=False,
        ),
    ]
